# Generated by Django 3.2.7 on 2021-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/media/images/joni-rajala-1qJh1aORn_Q-unsplash.jpg', null=True, upload_to='images/'),
        ),
    ]
