databases:
  - name: insta
    plan: free
    databaseName: insta
    user: postgres

services:
  - type: web
    plan: free
    name: insta
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn insta.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
