# Generated by Django 3.2.7 on 2021-09-14 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/'),
        ),
    ]
